# Generated by Django 2.2.5 on 2019-09-24 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonné',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_abonné', models.CharField(max_length=250)),
                ('adr_abonné', models.CharField(max_length=250)),
                ('tel_abonné', models.CharField(max_length=15)),
                ('date_adh', models.DateField(auto_now_add=True)),
                ('date_nais', models.DateField()),
                ('cat_prof', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_auteur', models.CharField(max_length=225)),
                ('adr_auteur', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_edit', models.CharField(max_length=225)),
                ('adr_edit', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mot_Cle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_mot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rayon', models.IntegerField()),
                ('loc_rayon', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_th', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_dem_pret', models.DateField(auto_now_add=True)),
                ('date_pret', models.DateField()),
                ('date_depot', models.DateField()),
                ('date_retour', models.DateField()),
                ('preteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ma_bibliotheque.Abonné')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_livre', models.CharField(max_length=50, unique=True)),
                ('nom_livre', models.CharField(max_length=100)),
                ('auteur', models.ManyToManyField(to='ma_bibliotheque.Auteur')),
                ('mots_clés', models.ManyToManyField(to='ma_bibliotheque.Mot_Cle')),
                ('rayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ma_bibliotheque.Rayon')),
                ('themes', models.ManyToManyField(to='ma_bibliotheque.Theme')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cote_livre', models.CharField(max_length=50, unique=True)),
                ('etat_usure', models.CharField(max_length=50)),
                ('editeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ma_bibliotheque.Editeur')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ma_bibliotheque.Livre')),
                ('pret', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ma_bibliotheque.Pret')),
            ],
        ),
    ]
