# Generated by Django 2.2.5 on 2019-09-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='pret',
        ),
        migrations.AddField(
            model_name='pret',
            name='livre',
            field=models.ManyToManyField(to='ma_bibliotheque.Exemplaire'),
        ),
    ]
