# Generated by Django 2.2.5 on 2019-09-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ma_bibliotheque', '0004_auto_20190926_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exemplaire',
            name='date_acquisition',
        ),
    ]
