# Generated by Django 2.2.5 on 2019-09-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ma_bibliotheque', '0006_exemplaire_date_acquisition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pret',
            old_name='date_retour',
            new_name='date_effective_de_retour',
        ),
        migrations.AlterField(
            model_name='exemplaire',
            name='date_acquisition',
            field=models.DateField(),
        ),
    ]
